const avatar = [
    {
        avatar_img:'/img/avatars/avatar-1.png'
    },
    {
        avatar_img:'/img/avatars/avatar-2.png'
    },
    {
        avatar_img:'/img/avatars/avatar-3.png'
    },
    {
        avatar_img:'/img/avatars/avatar-4.png'
    },
    {
        avatar_img:'/img/avatars/avatar-5.png'
    },
    {
        avatar_img:'/img/avatars/avatar-6.png'
    },
    {
        avatar_img:'/img/avatars/avatar-7.png'
    },
    {
        avatar_img:'/img/avatars/avatar-8.png'
    },
    {
        avatar_img:'/img/avatars/avatar-9.png'
    },
    {
        avatar_img:'/img/avatars/avatar-10.png'
    },
    {
        avatar_img:'/img/avatars/avatar-11.png'
    },
    {
        avatar_img:'/img/avatars/avatar-12.png'
    },
    {
        avatar_img:'/img/avatars/avatar-13.png'
    },
    {
        avatar_img:'/img/avatars/avatar-14.png'
    },
    {
        avatar_img:'/img/avatars/avatar-15.png'
    },
]

export default avatar